const technicianData = [
  {
    id: 1,
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 550,
    rating: 4.8,
  },
  {
    id: 2,
    avatar: require("../../../../images/avatar2.jpg"),
    name: "Chioma Okoye",
    role: "Nail Specialist",
    age: 28,
    clients: 490,
    rating: 4.6,
  },
  {
    id: 3,
    avatar: require("../../../../images/avatar3.jpg"),
    name: "Cynthia Nnaji",
    role: "Hair Stylist",
    age: 25,
    clients: 410,
    rating: 5.0,
  },
  {
    id: 4,
    avatar: require("../../../../images/avatar4.jpg"),
    name: "Olamide Rukky",
    role: "Nail Specialist",
    age: 24,
    clients: 504,
    rating: 4.7,
  },
  {
    id: 5,
    avatar: require("../../../../images/avatar5.jpg"),
    name: "Omotayo Simi",
    role: "Hair Stylist",
    age: 30,
    clients: 470,
    rating: 4.2,
  },
  {
    id: 6,
    avatar: require("../../../../images/avatar6.jpg"),
    name: "Fumi Emuakpo",
    role: "Nail Specialist",
    age: 20,
    clients: 520,
    rating: 4.9,
  },
  {
    id: 7,
    avatar: require("../../../../images/avatar7.jpg"),
    name: "Tochi Lynda",
    role: "Hair Stylist",
    age: 29,
    clients: 390,
    rating: 4.7,
  },
  {
    id: 8,
    avatar: require("../../../../images/avatar8.jpg"),
    name: "Kamara Udoka",
    role: "Hair Stylist",
    age: 21,
    clients: 500,
    rating: 4.9,
  },
  {
    id: 9,
    avatar: require("../../../../images/avatar9.jpg"),
    name: "Lovelyn Edeh",
    role: "Nail Specialist",
    age: 32,
    clients: 470,
    rating: 4.6,
  },
];
export default technicianData;
