const technicianData = [
  {
    id: 1,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 2,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Chioma Okoye",
    role: "Nail Specialist",
    age: 28,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 3,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Cynthia Nnaji",
    role: "Hair Stylist",
    age: 25,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 4,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Olamide Rukky",
    role: "Nail Specialist",
    age: 24,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 5,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Omotayo Simi",
    role: "Hair Stylist",
    age: 30,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 6,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Fumi Emuakpo",
    role: "Nail Specialist",
    age: 20,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 7,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Tochi Lynda",
    role: "Hair Stylist",
    age: 29,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 8,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Kamara Udoka",
    role: "Hair Stylist",
    age: 21,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 9,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Lovelyn Edeh",
    role: "Nail Specialist",
    age: 32,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
];
export default technicianData;
