const technicianData = [
  {
    id: 1,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 2,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 3,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 4,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 5,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 6,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 7,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 8,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
  {
    id: 9,
    tick: require("../../../../images/tick.png"),
    avatar: require("../../../../images/avatar1.png"),
    name: "Ademide Ruth",
    role: "Hair Stylist",
    age: 26,
    clients: 570,
    rating: 4.6,
    btn: false,
  },
];
export default technicianData;
